name: MOTD
version: 3.0
main: me.jason.motd.Motd
author: jason szot
description: an even more advanced message of the day with permissions

commands:
  motd:
    usage: /<command>
    description: display MOTD
  setmotd:
    usage: /<command>
    description: sets the MOTD
    
permissions:
  motd.set:
    description: use the setmotd command to change the MOTD
    default: op