name: MOTD
version: 2.0
main: me.jason.motd.Motd
author: jason szot
description: a more advanced message of the day

commands:
  motd:
    usage: /<command>
    description: display MOTD
  setmotd:
    usage: /<command>
    description: sets the MOTD