name: teleport
version: 1.0
main: me.jason.teleport.Teleport
author: jason szot
description: simple teleport plugin

commands:
  tp:
    usage: /<command>
    aliases: [teleport]
    description: teleports to a player
  setspawn:
    usage: /<command>
    aliases: [sspawn]
    description: sets the spawn
  spawn:
    usage: /<command>
    description: teleport to spawn